
language: python
# python versions to use during the tests
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
    - pip install -r dev-requirements.txt
    - pip install .
    - pip install pytest-cov codecov
# command to run tests
script:
   - pytest --cov=codecov
branches:
  only:
   - main
   - dev
after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - htwangtw@gmail.com
    on_success: always
    on_failure: always
